spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/boot_social_network
        username: root
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        properties:
            hibernate:
                format_sql: true

    mail:
        host: msn_mail_dev
        port: 1025
        username: root
        password: root
        properties:
            mail:
                smtp:
                    trust: "*"
                auth: true
                starttls:
                    enable: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000

application:
    security:
        jwt:
            secret-key: AE971E4D3DD31EC445DBA3EA21D29AE971E4D3DD31EC445DBA3EA21D29AE971E4D3DD31EC445DBA3EA21D29
            expiration: 8640000
    mailing:
        frontend:
            activation_url: http://localhost:4200/activate-account
    file:
        upload:
            photos-output-path: ./upload
server:
    port: 8088
