spring:
  datasource:
    url: jdbc:postgresql://ms_pg_sql:5432/product
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1  # Mettez à jour la version de base si nécessaire
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8050
