services:
    mongodb:
        image: mongo
        container_name: chv2_mongo_db
        ports:
            - 27018:27017
        volumes:
            - mongo:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        networks:
            - chatV2-net

    mongo-express:
        container_name: chatV2_mongo_express
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
            - ME_CONFIG_MONGODB_SERVER=chv2_mongo_db
            - ME_CONFIG_BASICAUTH_USERNAME=root
            - ME_CONFIG_BASICAUTH_PASSWORD=root
        networks:
            - chatV2-net


networks:
    chatV2-net:
        driver: bridge

volumes:
    mongo: { }
