spring:
  mvc:
    format:
      date: d/M/yyyy
  application:
    name: backend-student-management
  datasource:
    url: jdbc:h2:mem:students-db
  h2:
    console:
      enabled: true
server:
  port: 8021
